// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package books

import (
	"encoding/json"
	"time"

	openai "github.com/sashabaranov/go-openai"
)

type Batch struct {
	ID         string
	Super      *string
	Quo        openai.BatchStatus
	Body       openai.Batch
	CreatedAt  time.Time
	UpdatedAt  *time.Time
	CanceledAt *time.Time
}

type BatchOp struct {
	Batch       string
	CustomID    string
	Op          openai.BatchEndpoint
	Request     json.RawMessage
	Response    json.RawMessage
	CreatedAt   time.Time
	CompletedAt *time.Time
	CanceledAt  *time.Time
}

type Migration struct {
	Epoch int64
}
