// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package books

import (
	"time"

	openai "github.com/sashabaranov/go-openai"
)

type Batch struct {
	ID          string       `db:"id" json:"id"`
	Super       *string      `db:"super" json:"super"`
	Model       string       `db:"model" json:"model"`
	Body        openai.Batch `db:"body" json:"body"`
	CreatedAt   time.Time    `db:"created_at" json:"created_at"`
	UpdatedAt   *time.Time   `db:"updated_at" json:"updated_at"`
	CompletedAt *time.Time   `db:"completed_at" json:"completed_at"`
	CanceledAt  *time.Time   `db:"canceled_at" json:"canceled_at"`
}

type BatchOp struct {
	Batch       string             `db:"batch" json:"batch"`
	CustomID    string             `db:"custom_id" json:"custom_id"`
	Request     openai.BatchInput  `db:"request" json:"request"`
	Response    openai.BatchOutput `db:"response" json:"response"`
	Implicit    bool               `db:"implicit" json:"implicit"`
	Deferred    bool               `db:"deferred" json:"deferred"`
	CreatedAt   time.Time          `db:"created_at" json:"created_at"`
	UpdatedAt   *time.Time         `db:"updated_at" json:"updated_at"`
	CompletedAt *time.Time         `db:"completed_at" json:"completed_at"`
	CanceledAt  *time.Time         `db:"canceled_at" json:"canceled_at"`
}

type Migration struct {
	Epoch int64 `db:"epoch" json:"epoch"`
}
